var res = {
    HelloWorld_png : "res/HelloWorld.png",
    CloseNormal_png : "res/CloseNormal.png",
    locked_cell_bg_png : "res/JPC_Assets/locked-cell-bg.png",
    stone1_png : "res/JPC_Assets/stone1.png",
    sky_bg_png : "res/JPC_Assets/sky-bg.png",
    storage_png : "res/JPC_Assets/storage-1.png",
    land_thick_line_png:"res/JPC_Assets/land-thick-line.png",
    warehouse_png:"res/JPC_Assets/warehouse-1.png",
    storage_png:"res/JPC_Assets/storage-1.png",
    hand_png:"res/JPC_Assets/hand.png",
    male_png:"res/JPC_Assets/male.png",
    female_png:"res/JPC_Assets/female.png",
    cart_png:"res/JPC_Assets/cart.png",
    wood_png:"res/JPC_Assets/wood.png",
    blur_png:"res/JPC_Assets/blur.png",
    blur2_png:"res/JPC_Assets/blur2.png",
    earthDragon_png:"res/Buy_Panel/earth.png",
    earthblue_png:"res/Buy_Panel/earthblue.png",
    earthRed_png:"res/Buy_Panel/earthRed.png",
    evolve_btn2_png:"res/Buttons/evolve-btn2.png",
    breed_btn_png:"res/Buttons/breed-btn.png",
    dinosor1_png:"res/JPC_Assets/dinosor1.png",
    Shadow_png:"res/JPC_Assets/Shadow.png", 
    blurevolve_png:"res/JPC_Assets/blurevolve.png", 
    scroll0_png:"res/JPC_Assets/scroll0.png", 
    scroll1_png:"res/JPC_Assets/scroll1.png", 
    scroll2_png:"res/JPC_Assets/scroll2.png", 
    scroll4_png:"res/JPC_Assets/scroll4.png", 
    logo_png:"res/JPC_Assets/logo.png", 
    play_png:"res/Buttons/play.png",
    rightarrow_png:"res/Buttons/rightarrow.png",
    leftarrow_png:"res/Buttons/leftarrow.png",
    dinosor2_png:"res/JPC_Assets/dinosor2.png",
    dinosor3_png:"res/JPC_Assets/dinosor3.png",
    dinosor4_png:"res/JPC_Assets/dinosor4.png",
    dleft_png:"res/JPC_Assets/dragonleft.png",
    dright_png:"res/JPC_Assets/dragonright.png",
    rightRed_png:"res/JPC_Assets/rightRed.png",
    leftRed_png:"res/JPC_Assets/leftRed.png",
    rightblue_png:"res/JPC_Assets/rightblue.png",
    flycoin_png:"res/JPC_Assets/fly-coin.png",
    cartcoin_png:"res/JPC_Assets/cart-coin.png",
    elevatorRail2_png:"res/JPC_Assets/elevatorRail2.png",
    elevatorRailEnd2_png:"res/JPC_Assets/elevatorRailEnd2.png",
    btn_buy_product_png:"res/JPC_Assets/btn-buy-product.png",
    doorlayer_png:"res/JPC_Assets/door-layer.png",
    production_cell_bg_narrow_png:"res/JPC_Assets/production-cell-bg-narrow.png",
    build_mine_png:"res/Buttons/build-mine-btn.png",
    CloseSelected_png : "res/CloseSelected.png",
    Main_Music : "res/music.mp3"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}